# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20191022_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('run_time', models.IntegerField(default=1)),
                ('released_at', models.DateTimeField(max_length=255)),
                ('cast', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='view',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='view',
            name='director',
        ),
        migrations.RemoveField(
            model_name='review',
            name='view',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='View',
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='project_app.Movie'),
            preserve_default=False,
        ),
    ]
