# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20191022_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released_at',
            field=models.IntegerField(default=1),
        ),
    ]
