# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_auto_20191023_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
