# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_movie_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pic',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
