# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_auto_20191024_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pic',
            field=models.FileField(default='static/project_app/images/reel.jpg', upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.FileField(default='/static/project_app/images/34AD2.jpg', upload_to='documents/%Y/%m/%d'),
        ),
    ]
